export const myEvents = [
  {
    id: 'e1',
    EventName: "AI in Education Conference",
    comingSoon: false,
    OrganizerName: "Dr. Sarah Adel",
    OrganizerTitle: "AI Researcher & Educator",
    OrganizerImage: "./images/sarah.png",
    OrganizerDetails1: "Expert in AI and its integration in education.",
    OrganizerDetails2: "Passionate about future tech in classrooms.",
    OrganizerDetails3: "Has delivered over 20 keynotes in international education-tech summits.",
    content: [
      "• Future of AI in Classrooms",
      "• Personalized Learning Systems",
      "• Ethical Considerations",
      "• AI Tools for Teachers",
      "• Real-world Case Studies",
    ],
    duration: "2 Days",
    Details: "Join the leading minds in education and AI to explore future-ready teaching solutions.",
    category: ["cs"],
    imgPath: "./images/e1.jpg",
    discountedPrice: 'Free',
    price: 0,
    date: "July 10–11, 2025",
    venue: "Cairo International Conference Center"
  },
    {
    id: 'e4',
    EventName: "Modern Photography Workshop",
    comingSoon: false,
    OrganizerName: "Lens Art Studio",
    OrganizerTitle: "Professional Photographers Collective",
    OrganizerImage: "./images/lens-art.png",
    OrganizerDetails1: "Learn the art of composition and lighting.",
    OrganizerDetails2: "Hands-on outdoor sessions.",
    OrganizerDetails3: "Post-processing tips and tricks.",
    content: [
      "• Camera Settings",
      "• Lighting Techniques",
      "• Outdoor Photography",
      "• Editing Basics",
    ],
    duration: "3 Days",
    Details: "Workshop for photography enthusiasts to master modern techniques.",
    category: ["art"],
    imgPath: "./images/e6.jpg",
    price: 150,
    discountedPrice: 120,
    date: "September 5–7, 2025",
    venue: "Giza Photography Center"
  },
    {
    id: 'e3',
   EventName: "Frontend Masterclass",
  comingSoon: false,
  OrganizerName: "Garden Route Institute",
  OrganizerTitle: "Tech Education Hub",
  OrganizerImage: "./images/frontend-masterclass-organizer.png",
  OrganizerDetails1: "Master HTML, CSS, and JavaScript essentials.",
  OrganizerDetails2: "Hands-on projects guided by industry experts.",
  OrganizerDetails3: "Enhance your frontend development skills.",
  content: [
    "• HTML & CSS Fundamentals",
    "• JavaScript Basics",
    "• Responsive Design Techniques",
    "• Interactive Web Components",
    "• Deployment Best Practices",
  ],
  duration: "6 Weeks",
  Details: "Kickstart your tech career with our comprehensive Frontend Masterclass, covering the essentials of web development.",
  category: ["cs"],
  imgPath: "./images/e10.jpg",
  price: 200,
  discountedPrice: 150,
  date: "13 January 2025",
  venue: "George Campus",
  },
  {
    id: 'e5',
    EventName: "Cybersecurity Essentials",
    comingSoon: false,
    OrganizerName: "SecureNet Institute",
    OrganizerTitle: "Cybersecurity Experts",
    OrganizerImage: "./images/securenet.png",
    OrganizerDetails1: "Protect your digital assets.",
    OrganizerDetails2: "Learn from top security professionals.",
    OrganizerDetails3: "Prepare for industry certifications.",
    content: [
      "• Network Security",
      "• Ethical Hacking",
      "• Risk Management",
      "• Incident Response",
    ],
    duration: "1 Week",
    Details: "Essential skills for anyone interested in cybersecurity careers.",
    category: ["cs"],
    imgPath: "./images/e5.jpg",
    price: 299,
    discountedPrice: 249,
    date: "October 1–7, 2025",
    venue: "Online"
  },
 

  {
    id: 'e6',
    EventName: "Digital Art Expo 2025",
    comingSoon: false,
    OrganizerName: "Visual Arts Club",
    OrganizerTitle: "Creative Collective",
    OrganizerImage: "./images/art-organizer.png",
    Details: "Explore and showcase groundbreaking digital artwork by talented creators.",
    category: ["art"],
    imgPath: "./images/e2.png",
    discountedPrice: 'Free',
    price: 0,
    date: "August 20, 2025",
    venue: "Alexandria Art Museum"
  },
  {
    id: 'e7',
    EventName: "UX/UI Bootcamp",
    comingSoon: true,
    OrganizerName: "Coming Soon",
    OrganizerTitle: "",
    OrganizerImage: "./images/coming-soon.png",
    Details: "Learn how to design user-friendly interfaces and prototypes with Figma.",
    category: ["cs"],
    imgPath: "./images/e4.jpg",
    price: 0,
    date: "Coming Soon",
    venue: "TBA"
  },
,
  {
    id: 'e5',
    EventName: "Cybersecurity Essentials",
    comingSoon: false,
    OrganizerName: "SecureNet Institute",
    OrganizerTitle: "Cybersecurity Experts",
    OrganizerImage: "./images/securenet.png",
    OrganizerDetails1: "Protect your digital assets.",
    OrganizerDetails2: "Learn from top security professionals.",
    OrganizerDetails3: "Prepare for industry certifications.",
    content: [
      "• Network Security",
      "• Ethical Hacking",
      "• Risk Management",
      "• Incident Response",
    ],
    duration: "1 Week",
    Details: "Essential skills for anyone interested in cybersecurity careers.",
    category: ["cs"],
    imgPath: "./images/e5.jpg",
    
    price: 299,
    discountedPrice: 249,
  },
   {
    id: 'e2',
    EventName: "Blockchain & Cryptocurrency Summit",
    comingSoon: false,
    OrganizerName: "CryptoWorld",
    OrganizerTitle: "Blockchain Innovators",
    OrganizerImage: "./images/cryptoworld.png",
    OrganizerDetails1: "Latest trends in blockchain technology.",
    OrganizerDetails2: "Investment strategies and security.",
    OrganizerDetails3: "Networking with industry leaders.",
    content: [
      "• Blockchain Fundamentals",
      "• Crypto Trading Strategies",
      "• DeFi and NFTs",
      "• Regulatory Landscape",
    ],
    duration: "2 Days",
    Details: "Deep dive into the future of decentralized finance and blockchain.",
    category: ["tech"],
    imgPath: "./images/e3.jpg",
    price: 350,
    discountedPrice: 300,
  },

   {
    id: 'e3',
    EventName: "Full-Stack Web Dev Bootcamp",
    comingSoon: false,
    OrganizerName: "Code Masters Academy",
    OrganizerTitle: "Leading coding bootcamp",
    OrganizerImage: "./images/code-masters.png",
    OrganizerDetails1: "Hands-on learning with industry projects.",
    OrganizerDetails2: "Experienced instructors with startup background.",
    OrganizerDetails3: "Build real-world apps with React and Node.js.",
    content: [
      "• JavaScript & ES6+",
      "• React and Redux",
      "• Node.js and Express",
      "• Database Management",
      "• Deployment and Hosting",
    ],
    duration: "4 Weeks",
    Details: "Intensive bootcamp for aspiring full-stack developers looking to launch their careers.",
    category: ["cs"],
    imgPath: "./images/e33.jpg",
    price: 499,
    discountedPrice: 399,
  },
  {
    id: 'e7',
    EventName: "Creative Writing Retreat",
    comingSoon: true,
    OrganizerName: "Writers' Haven",
    OrganizerTitle: "Authors & Poets",
    OrganizerImage: "./images/writers-haven.png",
    OrganizerDetails1: "Improve your storytelling skills.",
    OrganizerDetails2: "Workshops with published authors.",
    OrganizerDetails3: "Peer review and feedback sessions.",
    content: [
      "• Fiction & Non-fiction Writing",
      "• Poetry Crafting",
      "• Character Development",
      "• Publishing Insights",
    ],
    duration: "5 Days",
    Details: "Escape to focus on your creative writing with expert guidance.",
    category: ["art"],
    imgPath: "./images/e7.jpg",
    price: 400,
    discountedPrice: 350,
  },
  {
    id: 'e8',
    EventName: "Sustainable Living Expo",
    comingSoon: true,
    OrganizerName: "Green Earth Org",
    OrganizerTitle: "Environmental Advocates",
    OrganizerImage: "./images/green-earth.png",
    OrganizerDetails1: "Promoting eco-friendly lifestyles.",
    OrganizerDetails2: "Workshops on sustainable products.",
    OrganizerDetails3: "Community engagement activities.",
    content: [
      "• Renewable Energy",
      "• Zero Waste Practices",
      "• Sustainable Home Design",
      "• Eco-friendly Technologies",
    ],
    duration: "3 Days",
    Details: "Learn how to live greener and reduce your carbon footprint.",
    category: ["education", "environment"],
    imgPath: "./images/e8.jpg",
    price: 50,
    discountedPrice: 40,
  },
  {
    id: 'e9',
    EventName: "Yoga & Mindfulness Retreat",
    comingSoon: false,
    OrganizerName: "Harmony Wellness Center",
    OrganizerTitle: "Yoga Instructors & Therapists",
    OrganizerImage: "./images/harmony-wellness.png",
    OrganizerDetails1: "Reconnect with your mind and body.",
    OrganizerDetails2: "Daily guided yoga sessions.",
    OrganizerDetails3: "Mindfulness and meditation workshops.",
    content: [
      "• Hatha and Vinyasa Yoga",
      "• Stress Management",
      "• Breathing Techniques",
      "• Healthy Lifestyle Habits",
    ],
    duration: "7 Days",
    Details: "A holistic retreat to refresh your mental and physical health.",
    category: ["health", "wellness"],
    imgPath: "./images/e9.jpg",
    price: 600,
    discountedPrice: 550,
  },

];